export const AUTH_LOGIN_PENDING = "AUTH_LOGIN_PENDING";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_SIGNUP_PENDING = "AUTH_SIGNUP_PENDING";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_ERROR = "AUTH_SIGNUP_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESTORE_SESSION = "AUTH_RESTORE_SESSION";
