export const FETCH_WEATHER_PENDING = "FETCH_WEATHER_PENDING";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";

export const FETCH_FORECAST_PENDING = "FETCH_FORECAST_PENDING";
export const FETCH_FORECAST_ERROR = "FETCH_FORECAST_ERROR";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";

export const SET_CITY = "SET_CITY";
