export const AUTH_LOGIN_PENDING = "AUTH_LOGIN_PENDING";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_SIGNUP_PENDING = "AUTH_SIGNUP_PENDING";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_ERROR = "AUTH_SIGNUP_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESTORE_SESSION = "AUTH_RESTORE_SESSION";
export const AUTH_CHECK_COMPLETE = "AUTH_CHECK_COMPLETE";

export const AUTH_UPDATE_PREFERENCES = "AUTH_UPDATE_PREFERENCES";

export const AUTH_RESET_PASSWORD_PENDING = "AUTH_RESET_PASSWORD_PENDING";

export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";

export const AUTH_RESET_PASSWORD_ERROR = "AUTH_RESET_PASSWORD_ERROR";
